### ISSUE TITLE
The Narrate (Control menu) door hanger is wrongly displayed in front of the "Close Reader view" button instead of the "Narrate" button 

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/firefox-narrate-experiment#6]
**[Notes]:**
- The door hanger is correctly repositioned in front of the "Narrate" button after a browser resize, after the page is refreshed or after the sidebar buttons fron Narrate mode are clicked.

**[Affected versions]:**
- Firefox 65 Unbranded
- Firefox 66.0b9 Dev. Edition

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Narrate" add-on (0.3) custom build installed through "about:debugging".
- You are enrolled in the "feature-passive" or "feature-active" branch.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to the "https://en.wikipedia.org/wiki/Main_Page" website.
2. Click the headset icon from the Awesomebar. 
3. Observe the position of the Narrate (Control Menu) door hanger.

**[Expected result]:**
- The door hanger is displayed in front of the "Narrate" button.

**[Actual result]:**
- The door hanger is displayed in front of the "Close Reader view" button.

**[Additional Notes]:**
- This issue is reproducible only on the "feature-passive" and "feature-active" branches.
- Attached is a screen recording of the issue: 
![dorrhangerposition](https://user-images.githubusercontent.com/40061643/53029422-7b887500-3471-11e9-88a1-65e027875ffe.gif)

**Comment by awallin** [comment]
Because this is a quick experiment door hanger overlap is acceptable on certain scenarios/screen sizes. Close reader view button appears to remain accessible even with the slight overlap. Closing as won't fix.

**Comment by Gozala** [comment]
This is the same issues as #9 which was fixed no ?

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's still reproducible on MacOS platform, using the latest firefox-listen-study@mozilla.org-0.7-signed build.
However, this issue is no longer reproducible on Windows 10 platform.
Tested on Windows 10 and Mac 10.14 using Firefox RC 66.0. Build ID: 20190314174725.
